/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AtmoshereControl: typeof import('./components/GlobalControl/AtmoshereControl.vue')['default']
    BackGroundControl: typeof import('./components/GlobalControl/BackGroundControl.vue')['default']
    ChangeGlbStyle: typeof import('./components/ModelRelated/ChangeGlbStyle.vue')['default']
    ChangeModelPositionHdr: typeof import('./components/ModelRelated/ChangeModelPositionHdr.vue')['default']
    Cluster: typeof import('./components/VectorEffect/Cluster.vue')['default']
    CommonDraw: typeof import('./components/Draw/CommonDraw.vue')['default']
    CustomDataLayers: typeof import('./components/LayerManager/CustomDataLayers.vue')['default']
    EarthDataLayers: typeof import('./components/LayerManager/EarthDataLayers.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    FloodAnalysis: typeof import('./components/SpatialAnalysis/FloodAnalysis.vue')['default']
    MeasureTool: typeof import('./components/Measure/MeasureTool.vue')['default']
    MenuTree: typeof import('./components/Menu/MenuTree.vue')['default']
    MouseStatusInfo: typeof import('./components/MouseStatusInfo/MouseStatusInfo.vue')['default']
    PlaceNameSearch: typeof import('./components/VectorEffect/PlaceNameSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SituationPlotDraw: typeof import('./components/Draw/SituationPlotDraw.vue')['default']
  }
}
